### ISSUE TITLE
is it possible to add a scrollbar to browse the multiple enchantments other mods have to offer?

### ISSUE THREAD

**Issue by felipengoso** [BrassAmber-Mods/soulbound-armory#13]
or how can I do it?

**Comment by nnym** [comment]
I've been considering introducing a scrollbar to the enchantment tab recently. I appreciate your willingness to help; but based on your CurseForge comment, I don't think that you have the understanding of Java that you need in order to do it (but you may prove me wrong). If it was just a job of copying and pasting, then I might have done it already.

Closes auoeke/soulbound-armory#18. I tried to transfer the old issue here but GitHub didn't let me do so.

**Comment by felipengoso** [comment]
Thanks for the replying, I really don't understand that much to do so myself but I've tried in the past, when the mod was available for the 1.12 version. Still I am looking forward to this, because I used to play your mod alongside with the RAD modpack, which includes a lot of enchantments, but I couldn't use any useful because of this issue.

**Comment by felipengoso** [comment]
Is it working? I've downloaded the mod through github and played with Unique Enchantments but there was no scrollbar T.T

**Comment by nnym** [comment]
I have a somewhat functional scroll box but it still has some issues—for example buttons in a scroll box have to be clicked below where they are—so I haven't added it to the enchantment tab yet.

**Comment by felipengoso** [comment]
Understood, I'm looking forward this !!
